name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3 
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Run Tests
      run: |
        pytest

    - name: Deploy to EC2
      env:
        SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
      run: |
        ssh -i "prudhvi123.pem" ubuntu@ec2-3-91-50-213.compute-1.amazonaws.com 'bash -s' < deploy_script.sh

